# @software: PyCharm
# @author: Lionel Johnson
# @contact: https://fairy.host
# @organization: https://github.com/FairylandFuture
# @datetime: 2025-12-22 23:03:00 UTC+08:00
---
douban:
  redis:
    host: localhost
    port: 6379
    db: 15
    password: xxxx
  mysql:
    host: localhost
    port: 3306
    database: database
    user: root
    password: root
